language: groovy
jdk:
- oraclejdk7
branches:
  only:
  - master
before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- GRAILS_VERSION=`grep '^\s*app.grails.version' application.properties | sed -e 's/^\s*app\.grails\.version=//g'
  | tr -d "\r"`
- echo "GRAILS_VERSION:$GRAILS_VERSION"
- gvm install grails $GRAILS_VERSION || true
before_script:
- GRAILS_VERSION_NUMBER=`echo $GRAILS_VERSION | sed -e 's/\.[0-9]*$//g' -e 's/\.//g'`
- echo "GRAILS_VERSION_NUMBER:$GRAILS_VERSION_NUMBER"
- GRAILS_SETTINGS_FILE="travis_grails_settings_new.groovy"
- if [ "$GRAILS_VERSION_NUMBER" -lt "23" ]; then GRAILS_SETTINGS_FILE="travis_grails_settings_old.groovy";
  fi;
- echo "GRAILS_SETTINGS_FILE:$GRAILS_SETTINGS_FILE"
- mkdir -p ~/.grails; wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/$GRAILS_SETTINGS_FILE
- mkdir -p ~/.m2;     wget -q -O ~/.m2/settings.xml        https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
- MAVEN_REPO="ala-repo"
- MAVEN_REPO_URL="http://nexus.ala.org.au/content/repositories/snapshots/"
- grep '^\s*app\.version=' ./application.properties | grep -q "\-SNAPSHOT"; if [ "$?" = "1" ]; then MAVEN_REPO_URL="http://nexus.ala.org.au/content/repositories/releases/"; fi;
- echo "MAVEN_REPO:$MAVEN_REPO"
- echo "MAVEN_REPO_URL:$MAVEN_REPO_URL"

script:
- grails clean && grails refresh-dependencies --non-interactive && grails prod war
  --non-interactive
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && APP_VERSION=`grep "^\s*app\.version=" ./application.properties | sed -e "s/^\s*app\.version=//g" | tr -d "\r"` && APP_NAME=`grep "^\s*app\.name=" ./application.properties | sed -e "s/^\s*app\.name=//g" | tr -d "\r"` && cat grails-release-plugin-bug-workaround_pom.xml | sed -e "s/SET_ARTIFACT_ID/$APP_NAME/g" | sed -e "s/SET_NAME/$APP_NAME/g" > pom.xml && mvn versions:set -DnewVersion=$APP_VERSION && mvn deploy:deploy-file -DpomFile=pom.xml -Dfile=target/$APP_NAME-$APP_VERSION.war -DrepositoryId=$MAVEN_REPO -Durl=$MAVEN_REPO_URL'

env:
  global:
  - secure: XXXTssBnWIBinafmyop1zf/2Pf81hpr0IisjfUd9lw4InfnbICNChS6P/ovfdtFu062xeVYbAgUQLCec1KlPDZQ32UgxFGU74EQ/1M70bJULsxd35UBpTNkhUyNQIcr9DkOhMYahvQbmySv5JGVFiT9ry/38xzQsHfYCQPs5dJY=
  - secure: FHlKa+UKFJdz/4AlfIo6rspYR6+KGOND4hk13LJN3QZCHRjM2ij9toqDxP74aH4VGpaUzEaKy1cC8hqE2F97VbptrFo2NtDEl9fJ6Z/+3lPo3tr6PZ69WZqex//bO+kkpjEn0KspLc92cCfaVOJxHWu5QcQ+C1SddfTwY5FuHPU=
