dist: trusty
language: groovy
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
  - develop
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: Z6Jfqbjh+XtuJZpVEmBq3ZarQYG2Hb++md9uBKQeWyy23pM7Mh3S3enne3DNs7zyPEUYVr+udUZI5uGyKmjMKZqAgacZZeAtaj4tcJyZPJDzxCTyxzA+BlcYT3/tdmv/9jH4iwolp9CPHGZA69WhlttV9NLg9GBCpElfxi2bs7A=
  - secure: Bl6/Y0aI9Dq3CxZBJgES+M39O62+zkxzI93/6R0g0b7e86i6v5l319Y9fi3PLQ+YsIwJDMMSPvksKOLCk+e0WrizcdF21fDcJlHyO6WrnPoZIHA+dvMJ2AORIbHtBWo5KdczDmWR9/n2UkV6xwRZ0MRZ25bZLy3AsHh/I/5FMPA=
