---
grails:
    profile: web
    config:
        locations:
            - file:///data/specimenbrowser/config/specimenbrowser-config.properties
            - file:///data/specimenbrowser/config/specimenbrowser-config.yml
            - file:///data/specimenbrowser/config/specimenbrowser-config.groovy
    codegen:
        defaultPackage: au.org.ala.specimenbrowser
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
management:
    endpoints:
        jmx:
            unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
grails:
    serverURL: https://specimens.ala.org.au
bie:
    baseURL: https://bie.ala.org.au
    searchPath: /search
biocache:
    baseURL: https://biocache.ala.org.au
    servicesUrl: https://biocache-ws.ala.org.au/ws/
collectory:
    baseURL: https://collections.ala.org.au
    servicesUrl: https://collections.ala.org.au/ws/
    resourceMapping:
        - prefix: dr
          path: dataResource
        - prefix: co
          path: collection
        - prefix: in
          path: institution
        - prefix: dh
          path: dataHub
        - prefix: dp
          path: dataProvider
spatial:
    baseURL: https://spatial.ala.org.au
ala:
    baseURL: https://www.ala.org.au
    image:
        service:
            url: https://images.ala.org.au
security:
    cas:
        appServerName:  https://specimens.ala.org.au
        casServerName:   https://auth.ala.org.au
        uriFilterPattern:   /admin.*,/alaAdmin.*
skin:
    layout: main
    fluidLayout: true
    orgNameLong: Atlas of Living Australia
specimenbrowser:
    data:
        url: file:///data/specimenbrowser/config/data.json
headerAndFooter:
    baseURL: https://www.ala.org.au/commonui-bs3-2019
    version: 2
